apiVersion: v2
name: movie-reservation-system
description: Movie reservation system
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: redis
    version: 27.0.9
    repository: https://charts.bitnami.com/bitnami
  - name: kafka
    version: 32.3.10
    repository: https://charts.bitnami.com/bitnami

  