services:
  user-service:
    name: user-service

    replicaCount: 1

    image:
      repo: mquang279/user-service
      tag: v1
      pullPolicy: Always

    service:
      type: ClusterIP
      port: 80
      targetPort: 8080

    database:
      host: user-db
      port: 5432
      name: postgres

      secret:
        name: user-secret
        username: root
        password: mypassword

      configMap:
        name: user-config

  theater-service:
    name: theater-service

    replicaCount: 1

    image:
      repo: mquang279/theater-service
      tag: v1
      pullPolicy: Always

    service:
      type: ClusterIP
      port: 80
      targetPort: 8080

    database:
      host: theater-db
      port: 5432
      name: postgres

      secret:
        name: theater-secret
        username: root
        password: mypassword

      configMap:
        name: theater-config

  discovery-service:
    name: discovery-service

    replicaCount: 1

    image:
      repo: mquang279/discovery-service
      tag: v1
      pullPolicy: Always

    service:
      type: ClusterIP
      port: 8761
      targetPort: 8761

databases:
  user-db:
    name: user-db
    image:
      name: postgres
      tag: 17-alpine
      pullPolicy: IfNotPresent
    secret:
      name: user-db-secret
      username: root
      password: mypassword
    service:
      port: 5432
      targetPort: 5432
    resource:
      storage: 5Gi

  theater-db:
    name: theater-db
    image:
      name: postgres
      tag: 17-alpine
      pullPolicy: IfNotPresent
    secret:
      name: theater-db-secret
      username: root
      password: mypassword
    service:
      port: 5432
      targetPort: 5432
    resource:
      storage: 5Gi

global:
  security:
    allowInsecureImages: true

redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    count: 1
  replica:
    replicaCount: 0

kafka:
  image:
    registry: docker.io
    repository: bitnamilegacy/kafka
    tag: "4.0.0-debian-12-r10"
  clusterId: "abcdefghijklmnopqrstuv"
  kraft:
    enabled: true

  zookeeper:
    enabled: false

  controller:
    replicaCount: 1

  broker:
    replicaCount: 0

  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
    external:
      protocol: PLAINTEXT

  auth:
    enabled: false

  tls:
    enabled: false
