apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.userService.name }}
spec:
  replicas: {{ .Values.userService.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Values.userService.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.userService.name }}

    spec:
      containers:
        - name: {{ .Values.userService.name }}
          image: {{ .Values.userService.image.repo }}:{{ .Values.userService.image.tag }}
          imagePullPolicy: {{ .Values.userService.image.pullPolicy }}

          ports:
          - containerPort: {{ .Values.userService.service.targetPort }}
          
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.userService.database.configMap.name }}
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.userService.database.configMap.name }}
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.userService.database.configMap.name }}
                  key: DB_NAME

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.userService.database.secret.name }}
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.userService.database.secret.name }}
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.userService.name }}
spec:
  type: {{ .Values.userService.service.type }}
  selector:
    app: {{ .Values.userService.name }}
  ports:
    - port: {{ .Values.userService.service.port }}
      targetPort: {{ .Values.userService.service.targetPort }}
---
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Values.userService.database.configMap.name }}

data:
  DB_HOST: {{ .Values.userService.database.host | quote }}
  DB_PORT: {{ .Values.userService.database.port | quote }}
  DB_NAME: {{ .Values.userService.database.name | quote }}
---
apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.userService.database.secret.name }}

type: Opaque

stringData:
  DB_USERNAME: {{ .Values.userService.database.secret.username | quote }}
  DB_PASSWORD: {{ .Values.userService.database.secret.password | quote }}
---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: {{ .Values.databases.user.name }}
  labels:
    app: {{ .Values.databases.user.name }}

spec:
  serviceName: {{ .Values.databases.user.name }}
  replicas: 1

  selector:
    matchLabels:
      app: {{ .Values.databases.user.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.databases.user.name }}

    spec:
      containers:
        - name: {{ .Values.databases.user.image.name }}
          image: {{ .Values.databases.user.image.name }}:{{ .Values.databases.user.image.tag }}
          imagePullPolicy: {{ .Values.databases.user.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.databases.user.service.port }}

          env:
            - name: POSTGRES_DB
              value: postgres

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.databases.user.secret.name }}
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.databases.user.secret.name }}
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
    - metadata:
        name: postgres-data

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: {{ .Values.databases.user.resource.storage }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.databases.user.secret.name }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.databases.user.secret.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.databases.user.secret.password | quote }}
---
apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.databases.user.name }}

spec:
  clusterIP: None

  selector:
    app: {{ .Values.databases.user.name }}

  ports:
    - port: {{ .Values.databases.user.service.port}}
      targetPort: {{ .Values.databases.user.service.targetPort}}
